import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import {Box, Heading, Text, Center, Accordion, AccordionItem,AccordionButton, UnorderedList ,AccordionPanel, ListItem, AccordionIcon, Container, Flex} from '@chakra-ui/react'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Box bg='main.100' textAlign={'center'} w='100%' justifyContent={'center'}  m={'auto'}>
          <Center>
          <Heading width='400px' justifyContent={'center'} textAlign={'center'}>
          Welcome to the C4 evaluation for
RCT-201
          </Heading>
          </Center>
          <br />
          <br />
          <Center>
          <Text textAlign={'center'} width='800px'>You need to create an application similar to the one that you are looking right now. There 2 pages that needs to be created apart from the current homepage.</Text>
          </Center>

          <br />
          <br />
          <Center>
          <Text textAlign={'center'} width='800px'>One path is /people and another a dynamic route /people/[id]</Text>
          </Center>

          <Accordion w='70%' m={'auto'} mt='100px' textAlign={'left'}>
  <AccordionItem>
    <h2>
      <AccordionButton>
        <Box as="span" flex='1' textAlign='left'>
        /people
        </Box>
        <AccordionIcon />
      </AccordionButton>
    </h2>
    <AccordionPanel pb={4}>
    <UnorderedList>
  <ListItem>The people can go to this page, by clicking the `People` tab in the Navbar</ListItem>
  <ListItem>The data should be fetched from https://jsonplaceholder.typicode.com/users (Users API call) using Static Site Generation (SSG) for this page.</ListItem>
  <ListItem>Hence the people page will be rendered from the server, with all the data present in the HTML file itself

</ListItem>
</UnorderedList></AccordionPanel>
  </AccordionItem>

  <AccordionItem>
    <h2>
      <AccordionButton>
        <Box as="span" flex='1' textAlign='left'>
        /people/[id]
        </Box>
        <AccordionIcon />
      </AccordionButton>
    </h2>
    <AccordionPanel pb={4}>
    <UnorderedList>
  <ListItem>The people can go to this page, by clicking the `Get Todos` button in the User Cards</ListItem>
  <ListItem>All the static HTML files, based on the static paths of the user id, should be created using SSG</ListItem>
  <ListItem>The HTML files should have the UserID:[id] data present in their HTML pages (Check screenshots for examples)
</ListItem>
<ListItem>The TodoData should be fetched from https://jsonplaceholder.typicode.com/users/$id/todos using Client Side Rendering, and shown in the UI after the page loads</ListItem>
<ListItem>Visting any other dynamic route based on the user id which is not in the API should show the 404 page. For example, from the Users API call, none of the user has the 97 user id, hence, visiting http://localhost:3000/people/97 should return 404 page</ListItem>
</UnorderedList>
    </AccordionPanel>
  </AccordionItem>
  <Flex mt={'100'} direction={['column','column', 'column', 'row']}>
  <Container>Marking Criteria:</Container>
  <Container>#TYPESCRIPT</Container>
  <Container>#REACT
</Container>
  <Container>#NEXTJS</Container>
  <Container>#CHAKRAUI</Container>
</Flex>
</Accordion>

        </Box>
      </main>
    </>
  )
}
